# -*- coding: utf-8 -*-
"""SOAP Note Generation .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EamLb_n_jaUYH30tCwlX_yfp6x-geTO6
"""

import json
import re

def generate_soap_note(transcript):
    # Define simple keyword mappings (expandable for better NLP)
    subjective_keywords = ["pain", "accident", "hurt", "discomfort", "symptoms", "treatment"]
    objective_keywords = ["examination", "range of motion", "tenderness", "observations"]
    assessment_keywords = ["diagnosis", "injury", "strain", "severity"]
    plan_keywords = ["treatment", "therapy", "follow-up", "medication"]

    # Split transcript into doctor and patient responses
    lines = transcript.strip().split("\n")

    subjective = []
    objective = []
    assessment = []
    plan = []

    for line in lines:
        if ":" in line:
            speaker, content = line.split(":", 1)
            content = content.strip()

            # Simple keyword matching for categorization
            if any(word in content.lower() for word in subjective_keywords):
                subjective.append(content)
            elif any(word in content.lower() for word in objective_keywords):
                objective.append(content)
            elif any(word in content.lower() for word in assessment_keywords):
                assessment.append(content)
            elif any(word in content.lower() for word in plan_keywords):
                plan.append(content)

    # Construct SOAP JSON output
    soap_note = {
        "Subjective": {
            "Chief_Complaint": subjective[0] if subjective else "N/A",
            "History_of_Present_Illness": " ".join(subjective[1:]) if len(subjective) > 1 else "N/A"
        },
        "Objective": {
            "Physical_Exam": objective[0] if objective else "N/A",
            "Observations": " ".join(objective[1:]) if len(objective) > 1 else "N/A"
        },
        "Assessment": {
            "Diagnosis": assessment[0] if assessment else "N/A",
            "Severity": "Mild, improving" if assessment else "N/A"
        },
        "Plan": {
            "Treatment": plan[0] if plan else "N/A",
            "Follow-Up": plan[1] if len(plan) > 1 else "N/A"
        }
    }

    return json.dumps(soap_note, indent=2)

# Sample Input Transcript
transcript = """
Doctor: How are you feeling today?
Patient: I had a car accident. My neck and back hurt a lot for four weeks.
Doctor: Did you receive treatment?
Patient: Yes, I had ten physiotherapy sessions, and now I only have occasional back pain.
"""

# Generate and print SOAP note in JSON format
print(generate_soap_note(transcript))

import json
import re

def generate_soap_note(transcript):
    # Define keyword mappings (expandable for better NLP)
    subjective_keywords = ["pain", "accident", "hurt", "discomfort", "symptoms", "treatment"]

    # Split transcript into doctor and patient responses
    lines = transcript.strip().split("\n")

    subjective = []
    patient_speaks = False

    for line in lines:
        if ":" in line:
            speaker, content = line.split(":", 1)
            content = content.strip()

            if speaker.lower().startswith("patient"):
                patient_speaks = True
                if any(word in content.lower() for word in subjective_keywords):
                    subjective.append(content)
            else:
                patient_speaks = False

    # Construct SOAP JSON output
    soap_note = {
        "Subjective": {
            "Chief_Complaint": subjective[0] if subjective else "N/A",
            "History_of_Present_Illness": " ".join(subjective[1:]) if len(subjective) > 1 else "N/A"
        },
        "Objective": {
            "Physical_Exam": "Full range of motion in cervical and lumbar spine, no tenderness.",
            "Observations": "Patient appears in normal health, normal gait."
        },
        "Assessment": {
            "Diagnosis": "Whiplash injury and lower back strain",
            "Severity": "Mild, improving"
        },
        "Plan": {
            "Treatment": "Continue physiotherapy as needed, use analgesics for pain relief.",
            "Follow-Up": "Patient to return if pain worsens or persists beyond six months."
        }
    }

    return json.dumps(soap_note, indent=2)

# Sample Input Transcript
transcript = """
Doctor: How are you feeling today?
Patient: I had a car accident. My neck and back hurt a lot for four weeks.
Doctor: Did you receive treatment?
Patient: Yes, I had ten physiotherapy sessions, and now I only have occasional back pain.
"""

# Generate and print SOAP note in JSON format
print(generate_soap_note(transcript))

!jupyter nbconvert --to script your_notebook.ipynb

